[theme]
primaryColor = "#007AFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#333333"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false